.PHONY: help dev dev-backend dev-frontend build up down restart logs health ps clean install seed test

# Colors for output
BLUE := \033[0;34m
GREEN := \033[0;32m
YELLOW := \033[0;33m
RED := \033[0;31m
NC := \033[0m # No Color

# Default target
.DEFAULT_GOAL := help

help: ## Show this help message
	@echo "$(BLUE)Alta AI Sales Platform - Available Commands$(NC)"
	@echo ""
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  $(GREEN)%-20s$(NC) %s\n", $$1, $$2}'
	@echo ""

# Development Commands
dev: ## Start development servers (backend + frontend)
	@echo "$(BLUE)Starting development servers...$(NC)"
	@make -j2 dev-backend dev-frontend

dev-backend: ## Start backend development server
	@echo "$(BLUE)Starting backend development server...$(NC)"
	@cd backend && npm run dev

dev-frontend: ## Start frontend development server
	@echo "$(BLUE)Starting frontend development server...$(NC)"
	@cd frontend && npm run dev

# Docker Commands
build: ## Build all Docker images
	@echo "$(BLUE)Building Docker images...$(NC)"
	@docker-compose build

up: ## Start all containers in detached mode
	@echo "$(BLUE)Starting containers...$(NC)"
	@docker-compose up -d
	@echo "$(GREEN)Containers started successfully!$(NC)"
	@echo "Frontend: http://localhost:3000"
	@echo "API Load Balancer: http://localhost:8080"
	@make health

up-build: ## Build and start all containers from scratch with seeded data
	@echo "$(BLUE)=== Starting Fresh Deployment ===$(NC)"
	@echo "$(YELLOW)Step 1: Cleaning up old containers and volumes...$(NC)"
	@docker-compose down -v 2>/dev/null || true
	@echo "$(YELLOW)Step 2: Building Docker images...$(NC)"
	@docker-compose build
	@echo "$(YELLOW)Step 3: Starting containers...$(NC)"
	@docker-compose up -d
	@echo "$(YELLOW)Step 4: Waiting for containers to be healthy...$(NC)"
	@sleep 10
	@echo "$(YELLOW)Step 5: Seeding database with test data...$(NC)"
	@docker-compose exec -T backend1 node -e "const{seedDatabase}=require('./dist/seed-data');seedDatabase().then(()=>process.exit(0));" 2>/dev/null || docker-compose exec -T backend1 npm run seed
	@echo ""
	@echo "$(GREEN)========================================$(NC)"
	@echo "$(GREEN)   Deployment Complete!$(NC)"
	@echo "$(GREEN)========================================$(NC)"
	@echo ""
	@echo "$(BLUE)Access Points:$(NC)"
	@echo "  Frontend:     $(GREEN)http://localhost:3000$(NC)"
	@echo "  API:          $(GREEN)http://localhost:8080/api$(NC)"
	@echo ""
	@echo "$(BLUE)Login Credentials:$(NC)"
	@echo "  Username:     $(GREEN)test$(NC)"
	@echo "  Password:     $(GREEN)test123$(NC)"
	@echo ""
	@make health

up-build-start: ## First-time setup: Create env files, build, and start everything (demo mode with dummy API keys)
	@echo "$(BLUE)=========================================$(NC)"
	@echo "$(BLUE)   First-Time Setup & Demo Launch$(NC)"
	@echo "$(BLUE)=========================================$(NC)"
	@echo ""
	@echo "$(YELLOW)Step 1: Creating environment files with demo values...$(NC)"
	@if [ ! -f .env.docker ]; then \
		echo "$(BLUE)  → Creating .env.docker with dummy API keys (frontend will work, AI features will be disabled)...$(NC)"; \
		echo "# Environment variables for Docker deployment - DEMO MODE" > .env.docker; \
		echo "# Generated by 'make up-build-start' - Replace with real keys for full functionality" >> .env.docker; \
		echo "" >> .env.docker; \
		echo "# JWT Secret (demo value)" >> .env.docker; \
		echo "JWT_SECRET=demo-jwt-secret-change-in-production-$(shell date +%s)" >> .env.docker; \
		echo "" >> .env.docker; \
		echo "# OpenAI API (dummy - AI features will not work)" >> .env.docker; \
		echo "OPENAI_API_KEY=sk-demo-key-not-valid" >> .env.docker; \
		echo "" >> .env.docker; \
		echo "# Vapi.ai (dummy - voice calls will not work)" >> .env.docker; \
		echo "VAPI_API_KEY=demo-vapi-key-not-valid" >> .env.docker; \
		echo "VAPI_PHONE_NUMBER=+1234567890" >> .env.docker; \
		echo "VAPI_ASSISTANT_ID=demo-assistant-id" >> .env.docker; \
		echo "" >> .env.docker; \
		echo "# Twilio (dummy - WhatsApp will not work)" >> .env.docker; \
		echo "TWILIO_ACCOUNT_SID=ACdemo-account-sid-not-valid" >> .env.docker; \
		echo "TWILIO_AUTH_TOKEN=demo-auth-token-not-valid" >> .env.docker; \
		echo "TWILIO_WHATSAPP_NUMBER=whatsapp:+14155238886" >> .env.docker; \
		echo "$(GREEN)  ✓ .env.docker created$(NC)"; \
	else \
		echo "$(GREEN)  ✓ .env.docker already exists$(NC)"; \
	fi
	@echo ""
	@echo "$(YELLOW)Step 2: Installing dependencies and generating lock files...$(NC)"
	@if [ ! -f backend/package-lock.json ]; then \
		echo "$(BLUE)  → Installing backend dependencies...$(NC)"; \
		cd backend && npm install; \
		echo "$(GREEN)  ✓ Backend dependencies installed$(NC)"; \
	else \
		echo "$(GREEN)  ✓ Backend package-lock.json exists$(NC)"; \
	fi
	@if [ ! -f frontend/package-lock.json ]; then \
		echo "$(BLUE)  → Installing frontend dependencies...$(NC)"; \
		cd frontend && npm install; \
		echo "$(GREEN)  ✓ Frontend dependencies installed$(NC)"; \
	else \
		echo "$(GREEN)  ✓ Frontend package-lock.json exists$(NC)"; \
	fi
	@echo ""
	@echo "$(YELLOW)Step 3: Cleaning up old containers and volumes...$(NC)"
	@docker-compose down -v 2>/dev/null || true
	@echo "$(GREEN)  ✓ Cleanup complete$(NC)"
	@echo ""
	@echo "$(YELLOW)Step 4: Building Docker images (this may take a few minutes)...$(NC)"
	@docker-compose build
	@echo "$(GREEN)  ✓ Docker images built$(NC)"
	@echo ""
	@echo "$(YELLOW)Step 5: Starting all containers...$(NC)"
	@docker-compose up -d
	@echo "$(GREEN)  ✓ Containers started$(NC)"
	@echo ""
	@echo "$(YELLOW)Step 6: Waiting for services to be ready (10 seconds)...$(NC)"
	@sleep 10
	@echo "$(GREEN)  ✓ Services ready$(NC)"
	@echo ""
	@echo "$(YELLOW)Step 7: Seeding database with demo data...$(NC)"
	@docker-compose exec -T backend1 node -e "const{seedDatabase}=require('./dist/seed-data');seedDatabase().then(()=>process.exit(0));" 2>/dev/null || docker-compose exec -T backend1 npm run seed
	@echo "$(GREEN)  ✓ Database seeded$(NC)"
	@echo ""
	@echo "$(GREEN)=========================================$(NC)"
	@echo "$(GREEN)   🎉 Setup Complete! Demo Ready!$(NC)"
	@echo "$(GREEN)=========================================$(NC)"
	@echo ""
	@echo "$(BLUE)📱 Access the Application:$(NC)"
	@echo "  Frontend UI:  $(GREEN)http://localhost:3000$(NC)"
	@echo "  API Backend:  $(GREEN)http://localhost:8080/api$(NC)"
	@echo ""
	@echo "$(BLUE)🔑 Login Credentials:$(NC)"
	@echo "  Username:     $(GREEN)test$(NC)"
	@echo "  Password:     $(GREEN)test123$(NC)"
	@echo ""
	@echo "$(YELLOW)⚠️  Demo Mode Notes:$(NC)"
	@echo "  • Frontend and UI fully functional"
	@echo "  • API keys are dummy values - AI features disabled"
	@echo "  • Voice calls and WhatsApp won't work (no valid API keys)"
	@echo "  • Perfect for UI/UX demonstration"
	@echo "  • To enable AI features: edit .env.docker with real API keys"
	@echo ""
	@echo "$(BLUE)📊 Checking Service Health:$(NC)"
	@docker-compose ps
	@echo ""
	@echo "$(BLUE)💡 Useful Commands:$(NC)"
	@echo "  View logs:    $(GREEN)make logs$(NC)"
	@echo "  Stop demo:    $(GREEN)make down$(NC)"
	@echo "  Restart:      $(GREEN)make restart$(NC)"
	@echo ""

down: ## Stop and remove all containers
	@echo "$(YELLOW)Stopping containers...$(NC)"
	@docker-compose down
	@echo "$(GREEN)Containers stopped$(NC)"

down-volumes: ## Stop containers and remove volumes
	@echo "$(RED)Stopping containers and removing volumes...$(NC)"
	@docker-compose down -v
	@echo "$(GREEN)Containers and volumes removed$(NC)"

restart: ## Restart all containers
	@echo "$(YELLOW)Restarting containers...$(NC)"
	@docker-compose restart
	@echo "$(GREEN)Containers restarted$(NC)"

restart-backend: ## Restart only backend containers
	@echo "$(YELLOW)Restarting backend containers...$(NC)"
	@docker-compose restart backend1 backend2
	@echo "$(GREEN)Backend containers restarted$(NC)"

restart-frontend: ## Restart only frontend container
	@echo "$(YELLOW)Restarting frontend container...$(NC)"
	@docker-compose restart frontend
	@echo "$(GREEN)Frontend container restarted$(NC)"

# Logs Commands
logs: ## View logs from all containers
	@docker-compose logs -f

logs-backend: ## View logs from backend containers
	@docker-compose logs -f backend1 backend2

logs-backend1: ## View logs from backend1 container
	@docker-compose logs -f backend1

logs-backend2: ## View logs from backend2 container
	@docker-compose logs -f backend2

logs-frontend: ## View logs from frontend container
	@docker-compose logs -f frontend

logs-lb: ## View logs from load balancer
	@docker-compose logs -f load_balancer

# Health Check Commands
health: ## Check health of all services
	@echo "$(BLUE)Checking service health...$(NC)"
	@echo ""
	@echo "$(YELLOW)Frontend:$(NC)"
	@curl -sf http://localhost:3000/health && echo "$(GREEN)✓ Healthy$(NC)" || echo "$(RED)✗ Unhealthy$(NC)"
	@echo ""
	@echo "$(YELLOW)Load Balancer:$(NC)"
	@curl -sf http://localhost:8080/lb-health && echo "$(GREEN)✓ Healthy$(NC)" || echo "$(RED)✗ Unhealthy$(NC)"
	@echo ""
	@echo "$(YELLOW)Backend (via LB):$(NC)"
	@curl -sf http://localhost:8080/api/health && echo "$(GREEN)✓ Healthy$(NC)" || echo "$(RED)✗ Unhealthy$(NC)"
	@echo ""
	@echo "$(YELLOW)Docker Container Status:$(NC)"
	@docker-compose ps

health-watch: ## Continuously watch health status (5s interval)
	@watch -n 5 make health

# Container Management
ps: ## Show container status
	@docker-compose ps

stats: ## Show container resource usage
	@docker stats $$(docker-compose ps -q)

exec-backend1: ## Open shell in backend1 container
	@docker-compose exec backend1 /bin/sh

exec-backend2: ## Open shell in backend2 container
	@docker-compose exec backend2 /bin/sh

exec-frontend: ## Open shell in frontend container
	@docker-compose exec frontend /bin/sh

exec-lb: ## Open shell in load balancer container
	@docker-compose exec load_balancer /bin/sh

# Installation Commands
install: ## Install dependencies for both backend and frontend
	@echo "$(BLUE)Installing backend dependencies...$(NC)"
	@cd backend && npm install
	@echo "$(BLUE)Installing frontend dependencies...$(NC)"
	@cd frontend && npm install
	@echo "$(GREEN)Dependencies installed successfully!$(NC)"

install-backend: ## Install backend dependencies
	@cd backend && npm install

install-frontend: ## Install frontend dependencies
	@cd frontend && npm install

# Database Commands
seed: ## Seed database with sample data (local)
	@echo "$(BLUE)Seeding database...$(NC)"
	@cd backend && npm run seed
	@echo "$(GREEN)Database seeded successfully!$(NC)"

seed-100: ## Seed database with 100 prospects (local)
	@echo "$(BLUE)Seeding database with 100 prospects...$(NC)"
	@cd backend && npm run seed-100
	@echo "$(GREEN)Database seeded with 100 prospects!$(NC)"

seed-docker: ## Seed database in Docker container
	@echo "$(BLUE)Seeding database in Docker...$(NC)"
	@docker-compose exec backend1 npm run seed
	@echo "$(GREEN)Database seeded successfully!$(NC)"

seed-docker-100: ## Seed 100 prospects in Docker container
	@echo "$(BLUE)Seeding 100 prospects in Docker...$(NC)"
	@docker-compose exec backend1 npm run seed-100
	@echo "$(GREEN)Database seeded with 100 prospects!$(NC)"

# Build Commands (Local)
build-backend: ## Build backend TypeScript
	@echo "$(BLUE)Building backend...$(NC)"
	@cd backend && npm run build
	@echo "$(GREEN)Backend built successfully!$(NC)"

build-frontend: ## Build frontend for production
	@echo "$(BLUE)Building frontend...$(NC)"
	@cd frontend && npm run build
	@echo "$(GREEN)Frontend built successfully!$(NC)"

# Testing Commands
test: ## Run tests
	@echo "$(BLUE)Running tests...$(NC)"
	@cd backend && npm test || true

test-calls: ## Test call functionality
	@echo "$(BLUE)Testing call functionality...$(NC)"
	@cd backend && npm run test-calls

test-vapi: ## Test Vapi integration
	@echo "$(BLUE)Testing Vapi integration...$(NC)"
	@cd backend && npm run test-vapi

# Clean Commands
clean: ## Clean build artifacts and node_modules
	@echo "$(RED)Cleaning build artifacts...$(NC)"
	@rm -rf backend/dist
	@rm -rf frontend/dist
	@rm -rf backend/node_modules
	@rm -rf frontend/node_modules
	@echo "$(GREEN)Clean complete!$(NC)"

clean-docker: ## Remove all Docker images and containers
	@echo "$(RED)Removing Docker containers and images...$(NC)"
	@docker-compose down -v --rmi all
	@echo "$(GREEN)Docker cleanup complete!$(NC)"

# Setup Commands
setup: install ## Initial setup (install dependencies + create env files)
	@echo "$(BLUE)Creating environment files...$(NC)"
	@test -f backend/.env || cp backend/.env.example backend/.env
	@test -f frontend/.env || cp frontend/.env.example frontend/.env
	@test -f .env.docker || cp .env.docker.example .env.docker
	@echo "$(GREEN)Setup complete!$(NC)"
	@echo "$(YELLOW)Please update the .env files with your API keys$(NC)"

setup-docker: ## Setup for Docker deployment
	@test -f .env.docker || cp .env.docker.example .env.docker
	@echo "$(YELLOW)Please update .env.docker with your API keys before running 'make up'$(NC)"

# Production Commands
prod-build: ## Build for production
	@make build-backend
	@make build-frontend
	@echo "$(GREEN)Production build complete!$(NC)"

prod-up: ## Start production containers
	@echo "$(BLUE)Starting production environment...$(NC)"
	@docker-compose up -d
	@echo "$(GREEN)Production environment started!$(NC)"

# Utility Commands
validate-env: ## Validate environment variables
	@echo "$(BLUE)Validating environment variables...$(NC)"
	@test -f .env.docker && echo "$(GREEN)✓ .env.docker exists$(NC)" || echo "$(RED)✗ .env.docker missing$(NC)"
	@test -f backend/.env && echo "$(GREEN)✓ backend/.env exists$(NC)" || echo "$(RED)✗ backend/.env missing$(NC)"
	@test -f frontend/.env && echo "$(GREEN)✓ frontend/.env exists$(NC)" || echo "$(RED)✗ frontend/.env missing$(NC)"

ports: ## Show which ports are in use
	@echo "$(BLUE)Port usage:$(NC)"
	@echo "  Frontend:       http://localhost:3000"
	@echo "  Load Balancer:  http://localhost:8080"
	@echo "  Backend API:    http://localhost:8080/api"

info: ## Show system information
	@echo "$(BLUE)System Information:$(NC)"
	@echo "  Docker Version: $$(docker --version)"
	@echo "  Docker Compose: $$(docker-compose --version)"
	@echo "  Node Version:   $$(node --version)"
	@echo "  NPM Version:    $$(npm --version)"
